common: &common
  adapter: postgresql
  username: dbtest
  password: dbtest
  host: localhost

development:
  <<: *common
  database: db_dev

test:
  <<: *common
  database: db_test
  min_messages: WARNING

production:
  <<: *common
  database: db_prod
  min_messages: WARNING
